### ISSUE TITLE
Go Live checklist

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/wcc#17]
## Type of Change

- Other (please clarify below)

## Summary
Just tracking list of tasks and TODOs to make this repo public

## Details
1. [x] Basic docs and README - #9 
1. [x] ~~Get website domain name (github pages?)~~ - I think using Netlify is fine for now
1. [x] Acquire npm publishing name (`files`) - https://github.com/thescientist13/wcc/pull/26
1. [x] Clean up `TODO`s + commented code - https://github.com/thescientist13/wcc/pull/26
1. [x] Contributing Guide - https://github.com/thescientist13/wcc/pull/26
1. [x] Examples - #54 
    - SSG (innerHTML), this website
    - progressive hydration
    - SSR
    - data loading w/ counter example
1. [x] Logo + favicon + open graph image
1. [x] Run Lighthouse for perf / a11y audit, `<meta>` tags - https://github.com/thescientist13/wcc/pull/26
1. [x] [Final styles](https://github.com/thescientist13/wcc/issues/17#issuecomment-1120233097) - https://github.com/thescientist13/wcc/pull/20
1. [x] Website responsiveness - #57 
    ![Screenshot 2022-05-23 at 21 43 42](https://user-images.githubusercontent.com/895923/170801344-396bfa05-a3ac-4b03-9f50-aa18479e7caa.png)
1. [x] Final README walk through - #54 
1. [x] Transfer to ProjectEvergreen and make public

### Nice To Have
1. [x] Table of Contents for Docs and Example pages
1. [x] PrismJS for code samples - https://github.com/thescientist13/wcc/pull/26
1. [x] Pull **simple.css** from npm / _node modules_ - https://github.com/thescientist13/wcc/pull/26

## Post Launch
1. Add to [projectevergreen.github.io projects](https://projectevergreen.github.io/projects/) page / personal blog post
